Add view users configuration flag
italia/spid-testenv2 pull request #265
Opened 2019-11-15 17:12 UTC by Undermaken

This PR adds the **can_view_users** configuration flag to enable/disable the access to users list section

| flag on  | flag off |
| ------------- | ------------- |
![Preferences](https://user-images.githubusercontent.com/822471/68961750-5db72900-07d3-11ea-802d-c8440a63a5db.png) | ![Privacy](https://user-images.githubusercontent.com/822471/68961751-5e4fbf80-07d3-11ea-8ff6-3da3c17e71a8.png)

2019-11-15 17:54 UTC, francescopersico requested changes

2019-11-15 17:54 UTC, francescopersico commented on testenv/server.py
> +            'can_view_users': self._config.can_view_users
@Undermaken please fix indentation

2019-11-15 17:57 UTC, Undermaken commented on testenv/server.py
> +            'can_view_users': self._config.can_view_users
fixed within b9d8cd2632c7ced722c065f1841662bcb581baae

2019-11-15 18:01 UTC, francescopersico requested changes

2019-11-15 18:01 UTC, francescopersico commented on conf/config.yaml.example
> +# Abilita (true) o disabilita (false) la possibilità di aggiungere nuovi utenti
Wrong comment

2019-11-15 18:03 UTC, Undermaken commented on conf/config.yaml.example
> +# Abilita (true) o disabilita (false) la possibilità di aggiungere nuovi utenti
updated within https://github.com/italia/spid-testenv2/pull/265/commits/5c2f4509ed8e621788c843365a2ec514bcd93e06

2019-11-15 18:04 UTC, francescopersico approved these changes

2019-11-15 18:07 UTC, francescopersico requested changes

2019-11-15 18:07 UTC, francescopersico commented on testenv/server.py
> +                'can_view_users': self._config.can_view_users
Please create a `can_view_users` variable as `can_add_user` on line 348.

2019-11-15 18:10 UTC, Undermaken commented on testenv/server.py
> +                'can_view_users': self._config.can_view_users
updated within https://github.com/italia/spid-testenv2/pull/265/commits/caf4dc7692396b6f980ae967fc54ca57268a7052

2019-11-25 13:39 UTC, alranel commented
I have mixed feelings about this. I'm afraid that the ability to hide the users page would encourage users to trust spid-testenv2 as a safe application which can be used in a production context. spid-testenv2 is only a development/demo tool and MUST NOT be used to secure production applications. With this constraint in mind, I can't see a scenario where hiding the Users page would make sense.

I think we should keep this PR open until someone suggests such a scenario. I'll be happy to merge it then :-)

2023-02-06 07:32 UTC, closed without merging